edf-image-common: Temporarily disable kernel-module-vcu
Temporarily disable packages that depend on kernel-module-vcu because
these modules do not build with the 6.18 kernel. Re-enable them once
kernel-module-vcu is buildable with the 6.18 kernel.

ERROR: kernel-module-vcu-1_6.12+git-r0 do_compile: oe_runmake failed
ERROR: kernel-module-vcu-1_6.12+git-r0 do_compile: ExecutionError('/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/temp/run.do_compile.307458', 1, None, None)
ERROR: Logfile of failure stored in: /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/temp/log.do_compile.307458
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 32 KERNEL_SRC=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source O=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-build-artifacts KERNEL_PATH=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source KERNEL_VERSION=6.18.0-xilinx-g366830631330 CC=aarch64-amd-linux-gcc    -fuse-ld=bfd -fcanon-prefix-map  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/git=/usr/src/debug/kernel-module-vcu/6.12+git  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/git=/usr/src/debug/kernel-module-vcu/6.12+git  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/git=/usr/src/debug/kernel-module-vcu/6.12+git  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/git=/usr/src/debug/kernel-module-vcu/6.12+git  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/recipe-sysroot=  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/recipe-sysroot=  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/recipe-sysroot-native=   -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source=/usr/src/kernel  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source=/usr/src/kernel  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-build-artifacts=/usr/src/kernel  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-build-artifacts=/usr/src/kernel  LD=aarch64-amd-linux-ld.bfd   AR=aarch64-amd-linux-ar  OBJCOPY=aarch64-amd-linux-objcopy  STRIP=aarch64-amd-linux-strip O=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-build-artifacts KBUILD_EXTRA_SYMBOLS=
| make -C /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source M=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/git O=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-build-artifacts modules
| make[1]: Entering directory '/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source'
| make[2]: Entering directory '/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/git'
|   CC [M]  al5e/al_enc.o
|   CC [M]  dmaproxy/dmaproxy.o
|   CC [M]  al5d/al_dec.o
|   CC [M]  al5e/enc_user.o
|   CC [M]  al5e/enc_mails_factory.o
|   CC [M]  al5d/dec_mails_factory.o
|   CC [M]  common/al_alloc.o
|   CC [M]  al5d/dec_user.o
|   CC [M]  common/al_alloc_ioctl.o
|   CC [M]  common/al_buffers_pool.o
|   CC [M]  common/al_char.o
|   CC [M]  common/al_codec.o
|   CC [M]  common/al_dmabuf.o
|   CC [M]  common/al_user.o
|   CC [M]  common/al_vcu.o
|   CC [M]  common/al_mail.o
|   CC [M]  common/al_codec_mails.o
|   CC [M]  common/al_mailbox.o
|   CC [M]  common/al_list.o
|   CC [M]  common/al_queue.o
|   CC [M]  common/mcu_interface.o
|   CC [M]  common/mcu_utils.o
|   CC [M]  common/al_group.o
|   CC [M]  common/xil_l2_prefetch.o
|   CC [M]  common/xil_clk.o
| common/xil_l2_prefetch.c:29:5: warning: no previous prototype for 'get_l2_color_bitdepth' [-Wmissing-prototypes]
|    29 | u32 get_l2_color_bitdepth(void *parent)
|       |     ^~~~~~~~~~~~~~~~~~~~~
| common/xil_l2_prefetch.c:41:5: warning: no previous prototype for 'get_l2_size_in_bits' [-Wmissing-prototypes]
|    41 | u32 get_l2_size_in_bits(void *parent)
|       |     ^~~~~~~~~~~~~~~~~~~
| common/xil_l2_prefetch.c:48:5: warning: no previous prototype for 'get_num_cores' [-Wmissing-prototypes]
|    48 | u32 get_num_cores(void *parent)
|       |     ^~~~~~~~~~~~~
| common/xil_l2_prefetch.c:59:5: warning: no previous prototype for 'get_core_frequency' [-Wmissing-prototypes]
|    59 | u32 get_core_frequency(void *parent)
|       |     ^~~~~~~~~~~~~~~~~~
| al5d/dec_mails_factory.c:43:6: warning: no previous prototype for 'write_decode_mail' [-Wmissing-prototypes]
|    43 | void write_decode_mail(struct al5_mail *mail,
|       |      ^~~~~~~~~~~~~~~~~
| common/al_user.c:163:6: warning: no previous prototype for 'al5_user_destroy_channel_resources' [-Wmissing-prototypes]
|   163 | void al5_user_destroy_channel_resources(struct al5_user *user)
|       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| common/al_group.c:157:6: warning: no previous prototype for 'print_cannot_retrieve_user' [-Wmissing-prototypes]
|   157 | void print_cannot_retrieve_user(struct device *dev, u32 mail_uid)
|       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~
| common/al_group.c:163:6: warning: no previous prototype for 'should_destroy_channel_on_bad_feedback' [-Wmissing-prototypes]
|   163 | bool should_destroy_channel_on_bad_feedback(u32 mail_uid)
|       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| common/al_group.c:175:18: warning: no previous prototype for 'retrieve_user' [-Wmissing-prototypes]
|   175 | struct al5_user *retrieve_user(struct al5_group *group, struct al5_mail *mail)
|       |                  ^~~~~~~~~~~~~
| common/al_group.c:204:5: warning: no previous prototype for 'try_to_deliver_to_user' [-Wmissing-prototypes]
|   204 | int try_to_deliver_to_user(struct al5_group *group, struct al5_mail *mail)
|       |     ^~~~~~~~~~~~~~~~~~~~~~
| common/al_group.c:231:6: warning: no previous prototype for 'handle_mail' [-Wmissing-prototypes]
|   231 | void handle_mail(struct al5_group *group, struct al5_mail *mail)
|       |      ^~~~~~~~~~~
| common/al_group.c:253:6: warning: no previous prototype for 'read_mail' [-Wmissing-prototypes]
|   253 | void read_mail(struct al5_group *group)
|       |      ^~~~~~~~~
| common/al_char.c:21:5: warning: no previous prototype for 'al5_setup_chrdev_region' [-Wmissing-prototypes]
|    21 | int al5_setup_chrdev_region(int *major, int base_minor, int nb_devs, char *desc)
|       |     ^~~~~~~~~~~~~~~~~~~~~~~
| common/al_char.c:40:5: warning: no previous prototype for 'al5_setup_cdev' [-Wmissing-prototypes]
|    40 | int al5_setup_cdev(struct cdev *cdev, const struct file_operations *fops,
|       |     ^~~~~~~~~~~~~~
| common/al_char.c:55:6: warning: no previous prototype for 'al5_clean_up_cdev' [-Wmissing-prototypes]
|    55 | void al5_clean_up_cdev(struct cdev *cdev)
|       |      ^~~~~~~~~~~~~~~~~
| In file included from /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/include/linux/module.h:23,
|                  from /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/include/linux/device/driver.h:21,
|                  from /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/include/linux/device.h:32,
|                  from /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/include/linux/cdev.h:8,
|                  from dmaproxy/dmaproxy.c:14:
| dmaproxy/dmaproxy.c:26:18: error: expected ',' or ';' before 'DMA_BUF'
|    26 | MODULE_IMPORT_NS(DMA_BUF);
|       |                  ^~~~~~~
| /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/include/linux/moduleparam.h:31:61: note: in definition of macro 'MODULE_INFO'
|    31 |                 = __MODULE_INFO_PREFIX __stringify(tag) "=" info
|       |                                                             ^~~~
| dmaproxy/dmaproxy.c:26:1: note: in expansion of macro 'MODULE_IMPORT_NS'
|    26 | MODULE_IMPORT_NS(DMA_BUF);
|       | ^~~~~~~~~~~~~~~~
| make[5]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/scripts/Makefile.build:287: dmaproxy/dmaproxy.o] Error 1
| make[4]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/scripts/Makefile.build:556: dmaproxy] Error 2
| make[4]: *** Waiting for unfinished jobs....
| In file included from /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/include/linux/module.h:23,
|                  from /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/include/linux/device/driver.h:21,
|                  from /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/include/linux/device.h:32,
|                  from ./common/../include/al_dmabuf.h:18,
|                  from common/al_dmabuf.c:18:
| common/al_dmabuf.c:28:18: error: expected ',' or ';' before 'DMA_BUF'
|    28 | MODULE_IMPORT_NS(DMA_BUF);
|       |                  ^~~~~~~
| /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/include/linux/moduleparam.h:31:61: note: in definition of macro 'MODULE_INFO'
|    31 |                 = __MODULE_INFO_PREFIX __stringify(tag) "=" info
|       |                                                             ^~~~
| common/al_dmabuf.c:28:1: note: in expansion of macro 'MODULE_IMPORT_NS'
|    28 | MODULE_IMPORT_NS(DMA_BUF);
|       | ^~~~~~~~~~~~~~~~
| common/xil_clk.c:29:5: warning: no previous prototype for 'xil_clk_set_up' [-Wmissing-prototypes]
|    29 | int xil_clk_set_up(struct platform_device *pdev, struct al5_codec_desc *codec,
|       |     ^~~~~~~~~~~~~~
| common/xil_clk.c:120:5: warning: no previous prototype for 'xil_clk_clean_up' [-Wmissing-prototypes]
|   120 | int xil_clk_clean_up(struct platform_device *pdev, struct al5_codec_desc *codec)
|       |     ^~~~~~~~~~~~~~~~
| common/al_dmabuf.c:211:14: warning: 'al5_dmabuf_kmap' defined but not used [-Wunused-function]
|   211 | static void *al5_dmabuf_kmap(struct dma_buf *dmabuf, unsigned long page_num)
|       |              ^~~~~~~~~~~~~~~
| common/al_codec.c:447:5: warning: no previous prototype for 'al5_setup_dma' [-Wmissing-prototypes]
|   447 | int al5_setup_dma(struct al5_codec_desc *codec)
|       |     ^~~~~~~~~~~~~
| make[5]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/scripts/Makefile.build:287: common/al_dmabuf.o] Error 1
| make[5]: *** Waiting for unfinished jobs....
| common/al_alloc.c:31:24: warning: no previous prototype for 'al5_alloc_dma_' [-Wmissing-prototypes]
|    31 | struct al5_dma_buffer *al5_alloc_dma_(struct device *dev, size_t size)
|       |                        ^~~~~~~~~~~~~~
|   LD [M]  al5d/al5d.o
|   LD [M]  al5e/al5e.o
| make[4]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/scripts/Makefile.build:556: common] Error 2
| make[3]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/Makefile:2010: .] Error 2
| make[2]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/Makefile:248: __sub-make] Error 2
| make[2]: Leaving directory '/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/git'
| make[1]: *** [Makefile:248: __sub-make] Error 2
| make[1]: Leaving directory '/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa53-mali-common/kernel-source'
| make: *** [Makefile:15: all] Error 2
| ERROR: oe_runmake failed
| WARNING: /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/temp/run.do_compile.307458:187 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/temp/run.do_compile.307458, line 187
| 	#2: die, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/temp/run.do_compile.307458, line 171
| 	#3: oe_runmake, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/temp/run.do_compile.307458, line 166
| 	#4: module_do_compile, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/temp/run.do_compile.307458, line 154
| 	#5: do_compile, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/temp/run.do_compile.307458, line 148
| 	#6: main, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-vcu/6.12+git/temp/run.do_compile.307458, line 200
ERROR: Task (/scratch/sandeep/yocto/2026.1/yp-edf/sources/poky/../meta-xilinx/meta-xilinx-multimedia/recipes-multimedia/vcu/kernel-module-vcu_6.12.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 11263 tasks of which 11075 didn't need to be rerun and 1 failed.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Message-ID: <20260117022901.84632-4-sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>