basecamp-disk-image: Disable standard image class behavior
We are not constructing a rootfs, but a multiple rootfs disk image.  Disable
all of the components that handle rootfs generation to avoid dependency issues.

These issues appear when rm_work is used as the system gets confused and can
attempt to install multiple host items that it doesnt need, triggering:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:extend_recipe_sysroot(d)
     0003:
File: '.../sources/poky/meta/classes-global/staging.bbclass', lineno: 619, function: extend_recipe_sysroot
     0615:                    if "/bin/" in l or "/sbin/" in l:
     0616:                        # defer /*bin/* files until last in case they need libs
     0617:                        binfiles[l] = (targetdir, dest)
     0618:                    else:
 *** 0619:                        staging_copyfile(l, targetdir, dest, postinsts, seendirs)
     0620:
     0621:    # Handle deferred binfiles
     0622:    for l in binfiles:
     0623:        (targetdir, dest) = binfiles[l]
File: '.../sources/poky/meta/classes-global/staging.bbclass', lineno: 165, function: staging_copyfile
     0161:        os.symlink(linkto, dest)
     0162:        #bb.warn(c)
     0163:    else:
     0164:        try:
 *** 0165:            os.link(c, dest)
     0166:        except OSError as err:
     0167:            if err.errno == errno.EXDEV:
     0168:                bb.utils.copyfile(c, dest)
     0169:            else:
Exception: FileExistsError: [Errno 17] File exists: '.../build/tmp/sysroots-components/cortexa72-cortexa53/libgcc-initial/usr/lib/aarch64-basecamp-linux/13.3.0/crtend.o' -> '.../build/tmp/work/versal_common-basecamp-linux/basecamp-disk-image/1.0/recipe-sysroot/usr/lib/aarch64-basecamp-linux/13.3.0/crtend.o'

Signed-off-by: Mark Hatle <mark.hatle@amd.com>