edf-image-common: Fix parse issue for amd-cortexa78-common
Fix parse issue for amd-cortexa78-common.

ERROR: Nothing RPROVIDES 'xen-zephyr-domu-image' (but /scratch/sandeep/yocto/2025.2/yp-edf/sources/poky/../meta-amd-edf/recipes-extended/images/edf-image-everything.bb RDEPENDS on or otherwise requires it)
xen-zephyr-domu-image was skipped: incompatible with machine amd-cortexa78-common (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'xen-zephyr-domu-image' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['xen-zephyr-domu-image']
ERROR: Nothing RPROVIDES 'edf-image-everything'
No eligible RPROVIDERs exist for 'edf-image-everything'

This is due to xen-zephyr-domu-image doesn't have COMPATIBLE_MACHINE
for versal-net.

Hence enable xen-zephyr-domu-image for versal and versal-2ve-2vm only.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Message-Id: <20251010145305.774726-1-sandeep.gundlupet-raju@amd.com>
Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>