amd-edf: Add wayland group to amd-edf user
Add wayland group to amd-edf user as this is required for running
weston applications.

Also below errors are seen with initramfs image.

ERROR: kria-image-initramfs-1.0-r0 do_rootfs: kria-image-initramfs: usermod command did not succeed.
ERROR: kria-image-initramfs-1.0-r0 do_rootfs: ExecutionError('/scratch/sandeep/yocto/2025.2/yp-dev-merge/build/tmp/work/kria_zynqmp_generic-amd-linux/kria-image-initramfs/1.0/temp/run.set_user_group.3646547', 1, None, None)
ERROR: Logfile of failure stored in: /scratch/sandeep/yocto/2025.2/yp-dev-merge/build/tmp/work/kria_zynqmp_generic-amd-linux/kria-image-initramfs/1.0/temp/log.do_rootfs.3646547
ERROR: Task (/scratch/sandeep/yocto/2025.2/yp-dev-merge/sources/poky/../meta-kria/recipes-core/images/kria-image-initramfs.bb:do_rootfs) failed with exit code '1

This is due to wayland group is created in weston-init recipe and it is
not avaiable in global configurations. Hence create a wayland group by
adding "groupadd -r wayland" in EXTRA_USERS_PARAMS.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Message-Id: <20251023230027.441945-1-sandeep.gundlupet-raju@amd.com>
Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>