amd-edf.conf: Set stress-ng as preferred stress tool
Set preferred provider of stress tool to stress-ng because with
the latest version of meta-ros, we otherwise have this conflict:

ERROR: Multiple .bb files are due to be built which each provide stress:
  meta-ros/meta-ros-common/recipes-devtools/stress/stress_1.0.7.bb
  poky/meta/recipes-extended/stress-ng/stress-ng_0.17.05.bb

Signed-off-by: Christian Kohn <chris.kohn@amd.com>
Message-ID: <20260129022334.119308-2-chris.kohn@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>