edf-image-common: Temporarily disable kernel-module-vcu2
Temporarily disable packages that depend on kernel-module-vcu2 because
these modules do not build with the 6.18 kernel. Re-enable them once
kernel-module-vcu2 is buildable with the 6.18 kernel.

ERROR: kernel-module-vcu2-6.12+git-r0 do_compile: oe_runmake failed
ERROR: kernel-module-vcu2-6.12+git-r0 do_compile: ExecutionError('/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/temp/run.do_compile.109721', 1, None, None)
ERROR: Logfile of failure stored in: /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/temp/log.do_compile.109721
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 32 KERNEL_SRC=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source O=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-build-artifacts KDIR=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-build-artifacts KERNEL_PATH=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source KERNEL_VERSION=6.18.0-xilinx-g366830631330 CC=aarch64-amd-linux-gcc    -fuse-ld=bfd -fcanon-prefix-map  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/git=/usr/src/debug/kernel-module-vcu2/6.12+git  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/git=/usr/src/debug/kernel-module-vcu2/6.12+git  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/git=/usr/src/debug/kernel-module-vcu2/6.12+git  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/git=/usr/src/debug/kernel-module-vcu2/6.12+git  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/recipe-sysroot=  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/recipe-sysroot=  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/recipe-sysroot-native=   -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source=/usr/src/kernel  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source=/usr/src/kernel  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-build-artifacts=/usr/src/kernel  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-build-artifacts=/usr/src/kernel  LD=aarch64-amd-linux-ld.bfd   AR=aarch64-amd-linux-ar  OBJCOPY=aarch64-amd-linux-objcopy  STRIP=aarch64-amd-linux-strip O=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-build-artifacts KBUILD_EXTRA_SYMBOLS=
| make -C /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source M=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/git O=/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-build-artifacts modules
| make[1]: Entering directory '/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source'
| make[2]: Entering directory '/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/git'
|   CC [M]  al_riscv/al_dmabuf.o
| In file included from /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source/include/linux/module.h:23,
|                  from /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source/include/linux/device/driver.h:21,
|                  from /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source/include/linux/device.h:32,
|                  from /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source/include/linux/dma-mapping.h:5,
|                  from al_riscv/al_dmabuf.h:20,
|                  from al_riscv/al_dmabuf.c:17:
| al_riscv/al_dmabuf.c:24:18: error: expected ',' or ';' before 'DMA_BUF'
|    24 | MODULE_IMPORT_NS(DMA_BUF);
|       |                  ^~~~~~~
| /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source/include/linux/moduleparam.h:31:61: note: in definition of macro 'MODULE_INFO'
|    31 |                 = __MODULE_INFO_PREFIX __stringify(tag) "=" info
|       |                                                             ^~~~
| al_riscv/al_dmabuf.c:24:1: note: in expansion of macro 'MODULE_IMPORT_NS'
|    24 | MODULE_IMPORT_NS(DMA_BUF);
|       | ^~~~~~~~~~~~~~~~
| make[5]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source/scripts/Makefile.build:287: al_riscv/al_dmabuf.o] Error 1
| make[4]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source/scripts/Makefile.build:556: al_riscv] Error 2
| make[3]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source/Makefile:2010: .] Error 2
| make[2]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source/Makefile:248: __sub-make] Error 2
| make[2]: Leaving directory '/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/git'
| make[1]: *** [Makefile:248: __sub-make] Error 2
| make[1]: Leaving directory '/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work-shared/amd-cortexa78-mali-common/kernel-source'
| make: *** [Makefile:13: all] Error 2
| ERROR: oe_runmake failed
| WARNING: /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/temp/run.do_compile.109721:187 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/temp/run.do_compile.109721, line 187
| 	#2: die, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/temp/run.do_compile.109721, line 171
| 	#3: oe_runmake, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/temp/run.do_compile.109721, line 166
| 	#4: module_do_compile, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/temp/run.do_compile.109721, line 154
| 	#5: do_compile, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/temp/run.do_compile.109721, line 148
| 	#6: main, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/temp/run.do_compile.109721, line 200
ERROR: Task (/scratch/sandeep/yocto/2026.1/yp-edf/sources/poky/../meta-xilinx/meta-xilinx-multimedia/recipes-multimedia/vcu2/kernel-module-vcu2_6.12.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 964 tasks of which 963 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /scratch/sandeep/yocto/2026.1/yp-edf/sources/poky/../meta-xilinx/meta-xilinx-multimedia/recipes-multimedia/vcu2/kernel-module-vcu2_6.12.bb:do_compile
    log: /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp/work/amd_cortexa78_mali_common-amd-linux/kernel-module-vcu2/6.12+git/temp/log.do_compile.109721
Summary: There were 2 ERROR messages, returning a non-zero exit code.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Message-ID: <20260117022901.84632-2-sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>