bootbin-version-string: Add versal2 machine to fix parse errors
Add versal2 machine compatible to fix parse errors.

ERROR: Nothing PROVIDES 'bootbin-version-string'
bootbin-version-string was skipped: incompatible with machine versal2-palmyra-se10-sdt-seg (not in COMPATIBLE_MACHINE)
ERROR: Required build target 'xilinx-bootbin' has no buildable providers.
Missing or unbuildable dependency chain was: ['xilinx-bootbin', 'bootbin-version-string']

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>