edf-image-common: Temporarily disable kernel-module-hdmi
Temporarily disable packages that depend on kernel-module-hdmi because
these modules do not build with the 6.18 kernel. Re-enable them once
kernel-module-hdmi is buildable with the 6.18 kernel.

ERROR: kernel-module-hdmi-6.12.1+git-r0 do_compile: oe_runmake failed
ERROR: kernel-module-hdmi-6.12.1+git-r0 do_compile: ExecutionError('/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/temp/run.do_compile.930018', 1, None, None)
ERROR: Logfile of failure stored in: /scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/temp/log.do_compile.930018
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 32 KERNEL_SRC=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-source O=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-build-artifacts KERNEL_PATH=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-source KERNEL_VERSION=6.18.0-xilinx-g984c6a3b9186 CC=aarch64-amd-linux-gcc    -fuse-ld=bfd -fcanon-prefix-map  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/git=/usr/src/debug/kernel-module-hdmi/6.12.1+git  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/git=/usr/src/debug/kernel-module-hdmi/6.12.1+git  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/git=/usr/src/debug/kernel-module-hdmi/6.12.1+git  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/git=/usr/src/debug/kernel-module-hdmi/6.12.1+git  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/recipe-sysroot=  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/recipe-sysroot=  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/recipe-sysroot-native=   -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-source=/usr/src/kernel  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-source=/usr/src/kernel  -fdebug-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-build-artifacts=/usr/src/kernel  -fmacro-prefix-map=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-build-artifacts=/usr/src/kernel  LD=aarch64-amd-linux-ld.bfd   AR=aarch64-amd-linux-ar  OBJCOPY=aarch64-amd-linux-objcopy  STRIP=aarch64-amd-linux-strip O=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-build-artifacts KBUILD_EXTRA_SYMBOLS=
| make -C /scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-source M=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/git O=/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-build-artifacts modules
| make[1]: Entering directory '/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-source'
| make[2]: Entering directory '/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/git'
|   CC [M]  hdmi/xilinx_drm_hdmi.o
| In file included from hdmi/phy-xilinx-vphy/xhdcp22_common.h:42,
|                  from hdmi/xilinx_drm_hdmi.c:64:
| hdmi/phy-xilinx-vphy/bigdigits.h:140:1: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
|   140 | volatile u32 mpSetZero(volatile u32 a[], size_t ndigits);
|       | ^~~~~~~~
| hdmi/xilinx_drm_hdmi.c:891:6: warning: no previous prototype for 'TxBrdgUnlockedCallback' [-Wmissing-prototypes]
|   891 | void TxBrdgUnlockedCallback(void *CallbackRef)
|       |      ^~~~~~~~~~~~~~~~~~~~~~
| hdmi/xilinx_drm_hdmi.c:901:6: warning: no previous prototype for 'TxBrdgOverflowCallback' [-Wmissing-prototypes]
|   901 | void TxBrdgOverflowCallback(void *CallbackRef)
|       |      ^~~~~~~~~~~~~~~~~~~~~~
| hdmi/xilinx_drm_hdmi.c:907:6: warning: no previous prototype for 'TxBrdgUnderflowCallback' [-Wmissing-prototypes]
|   907 | void TxBrdgUnderflowCallback(void *CallbackRef)
|       |      ^~~~~~~~~~~~~~~~~~~~~~~
| hdmi/xilinx_drm_hdmi.c:913:6: warning: no previous prototype for 'TxHdcpAuthenticatedCallback' [-Wmissing-prototypes]
|   913 | void TxHdcpAuthenticatedCallback(void *CallbackRef)
|       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
| hdmi/xilinx_drm_hdmi.c:937:6: warning: no previous prototype for 'TxHdcpUnauthenticatedCallback' [-Wmissing-prototypes]
|   937 | void TxHdcpUnauthenticatedCallback(void *CallbackRef)
|       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| hdmi/xilinx_drm_hdmi.c: In function 'xlnx_drm_hdmi_connector_get_modes':
| hdmi/xilinx_drm_hdmi.c:1147:14: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
|  1147 |         edid = drm_edid_raw(drm_edid);
|       |              ^
| hdmi/xilinx_drm_hdmi.c: At top level:
| hdmi/xilinx_drm_hdmi.c:1176:35: error: initialization of 'enum drm_mode_status (*)(struct drm_connector *, const struct drm_display_mode *)' from incompatible pointer type 'int (*)(struct drm_connector *, struct drm_display_mode *)' [-Werror=incompatible-pointer-types]
|  1176 |         .mode_valid             = xlnx_drm_hdmi_connector_mode_valid,
|       |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| hdmi/xilinx_drm_hdmi.c:1176:35: note: (near initialization for 'xlnx_drm_hdmi_connector_helper_funcs.mode_valid')
| cc1: some warnings being treated as errors
| make[5]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/scripts/Makefile.build:287: hdmi/xilinx_drm_hdmi.o] Error 1
| make[4]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/scripts/Makefile.build:556: hdmi] Error 2
| make[3]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/Makefile:2010: .] Error 2
| make[2]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-source/Makefile:248: __sub-make] Error 2
| make[2]: Leaving directory '/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/git'
| make[1]: *** [Makefile:248: __sub-make] Error 2
| make[1]: Leaving directory '/scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work-shared/amd-cortexa53-mali-common/kernel-source'
| make: *** [Makefile:7: all] Error 2
| ERROR: oe_runmake failed
| WARNING: /scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/temp/run.do_compile.930018:187 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/temp/run.do_compile.930018, line 187
| 	#2: die, /scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/temp/run.do_compile.930018, line 171
| 	#3: oe_runmake, /scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/temp/run.do_compile.930018, line 166
| 	#4: module_do_compile, /scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/temp/run.do_compile.930018, line 154
| 	#5: do_compile, /scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/temp/run.do_compile.930018, line 148
| 	#6: main, /scratch/sandeep/yocto/2026.1/yp-edf/build-zynqmp/tmp/work/amd_cortexa53_mali_common-amd-linux/kernel-module-hdmi/6.12.1+git/temp/run.do_compile.930018, line 200
ERROR: Task (/scratch/sandeep/yocto/2026.1/yp-edf/sources/poky/../meta-xilinx/meta-xilinx-core/recipes-kernel/hdmi/kernel-module-hdmi_6.12.1.bb:do_compile) failed with exit code '1'

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Message-ID: <20260117022901.84632-6-sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>