bblayers.conf.sample: Fix layer parse errors
layer parse errors are observed

$ bitbake core-image-full-cmdline
NOTE: Started PRServer with DBfile: /scratch/sandeep/yocto/2024.2/yp-bc/build/cache/prserv.sqlite3, Address: 127.0.0.1:40627, PID: 3837291
ERROR: Layer 'xilinx' depends on layer 'meta-arm', but this layer is not enabled in your configuration

Summary: There was 1 ERROR message, returning a non-zero exit code.
$

This is due to meta-xilinx layer now depends on meta-arm and
meta-arm-toolchain layers. Hence add these layers to
bblayers.conf.sample file.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>