packagegroup-xilinx-ros: Remove rqt-runtime-monitor package
meta-basecamp layer doesn't enable meta-qt5 but rqt-runtime-monitor
included as part of packagegroup-xilinx-ros packagegroup DEPENDS on
qt-gui and other qt packages which results in below parse failure.

ERROR: Nothing RPROVIDES 'rqt-runtime-monitor' (but /scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/../meta-xilinx/meta-xilinx-demos/dynamic-layers/meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-xilinx-ros.bb RDEPENDS on or otherwise requires it)
rqt-runtime-monitor was skipped: Recipe will be skipped because: qt5: rdepends on rqt-gui-py which depends qt-gui which depends on qtbase; pyqt5: rdepends on rqt-gui which depends on qt-gui which depends on python3-pyqt5 which requires pyqt5

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>