xilinx-mali400: Add weston service file for amd-edf user
1. Copy the weston.service file from poky layer to xilinx-mali400 dynamic
   layer.
2. Change the user from weston to amd-edf and group to video so that
   amd-edf user can run all the wayland application. DRM and Graphics
   subsystems are part of video group.

Example:

AMD Embedded Development Framework Linux distribution 25.05+release-89bffc2b3935adb03e4ac21d4e90928512c521b1 amd-edf ttyPS0

amd-edf login: amd-edf
You are required to change your password immediately (administrator enforced).
New password:
Retype new password:

WARNING: AMD Embedded Development Framework is a reference Yocto Project
distribution that should be used for testing and development purposes only.
It is recommended that you create your own distribution for production use.

amd-edf:~$ ls -la /usr/lib/libMali.so.9.0
lrwxrwxrwx 1 root root 31 May  1 17:32 /usr/lib/libMali.so.9.0 -> /usr/lib/wayland/libMali.so.9.0
amd-edf:~$ id amd-edf
uid=1001(amd-edf) gid=1001(amd-edf) groups=1001(amd-edf),19(input),29(audio),44(video),984(aie)
amd-edf:~$ echo $XDG_RUNTIME_DIR
/run/user/1001
amd-edf:~$ sudo systemctl start weston

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

For security reasons, the password you type will not be visible.

Password:
amd-edf:~$
amd-edf:~$ time -p glmark2-es2-wayland
=======================================================
    glmark2 2023.01
=======================================================
    OpenGL Information
    GL_VENDOR:      ARM
    GL_RENDERER:    Mali-400 MP
    GL_VERSION:     OpenGL ES 2.0 "12dd573"
    Surface Config: buf=16 r=5 g=6 b=5 a=0 depth=24 stencil=8 samples=0
    Surface Size:   800x600 windowed
=======================================================
[build] use-vbo=false: FPS: 557 FrameTime: 1.797 ms
[build] use-vbo=true: FPS: 670 FrameTime: 1.494 ms
[texture] texture-filter=nearest: FPS: 821 FrameTime: 1.219 ms
[texture] texture-filter=linear: FPS: 783 FrameTime: 1.278 ms
[texture] texture-filter=mipmap: FPS: 779 FrameTime: 1.285 ms
[shading] shading=gouraud: FPS: 329 FrameTime: 3.047 ms
[shading] shading=blinn-phong-inf: FPS: 385 FrameTime: 2.598 ms
[shading] shading=phong: FPS: 276 FrameTime: 3.624 ms
[shading] shading=cel: FPS: 268 FrameTime: 3.743 ms
[bump] bump-render=high-poly: FPS: 125 FrameTime: 8.038 ms
[bump] bump-render=normals: FPS: 726 FrameTime: 1.378 ms
[bump] bump-render=height: FPS: 560 FrameTime: 1.787 ms
[effect2d] kernel=0,1,0;1,-4,1;0,1,0;: FPS: 140 FrameTime: 7.174 ms
[effect2d] kernel=1,1,1,1,1;1,1,1,1,1;1,1,1,1,1;: FPS: 63 FrameTime: 16.040 ms
[pulsar] light=false:quads=5:texture=false: FPS: 1190 FrameTime: 0.841 ms
[desktop] blur-radius=5:effect=blur:passes=1:separable=true:windows=4: FPS: 57 FrameTime: 17.600 ms
[desktop] effect=shadow:windows=4: FPS: 333 FrameTime: 3.003 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 75 FrameTime: 13.336 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=subdata: FPS: 118 FrameTime: 8.505 ms
[buffer] columns=200:interleave=true:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 87 FrameTime: 11.586 ms
[ideas] speed=duration: FPS: 430 FrameTime: 2.327 ms
[jellyfish] <default>: FPS: 190 FrameTime: 5.286 ms
Error: SceneTerrain requires Vertex Texture Fetch support, but GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS is 0
[terrain] <default>: Unsupported
[shadow] <default>: FPS: 232 FrameTime: 4.314 ms
[refract] <default>: FPS: 20 FrameTime: 51.551 ms
[conditionals] fragment-steps=0:vertex-steps=0: FPS: 820 FrameTime: 1.220 ms
[conditionals] fragment-steps=5:vertex-steps=0: FPS: 251 FrameTime: 3.998 ms
[conditionals] fragment-steps=0:vertex-steps=5: FPS: 813 FrameTime: 1.231 ms
[function] fragment-complexity=low:fragment-steps=5: FPS: 363 FrameTime: 2.758 ms
[function] fragment-complexity=medium:fragment-steps=5: FPS: 171 FrameTime: 5.871 ms
[loop] fragment-loop=false:fragment-steps=5:vertex-steps=5: FPS: 362 FrameTime: 2.763 ms
[loop] fragment-steps=5:fragment-uniform=false:vertex-steps=5: FPS: 363 FrameTime: 2.761 ms
[loop] fragment-steps=5:fragment-uniform=true:vertex-steps=5: FPS: 363 FrameTime: 2.759 ms
=======================================================
                                  glmark2 Score: 396
=======================================================
real 324.09
user 56.73
sys 31.82
amd-edf:~$

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>